#!/usr/bin/env bash
set -euo pipefail

ENV_NAME="${DDCOLOR_CONDA_ENV:-ddcolor}"
ENV_DIR="${DDCOLOR_CONDA_ENV_PREFIX:-${HOME}/.conda/envs/${ENV_NAME}}"
MARKER_FILE="${ENV_DIR}/.ddcolor-devcontainer.sha256"
REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
ONNXRUNTIME_GPU_INDEX_URL="https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-11/pypi/simple/"
PYTHON_VERSION="3.9"
NVIDIA_SITE_PACKAGES_DIR="${ENV_DIR}/lib/python${PYTHON_VERSION}/site-packages/nvidia"
CUDA_LD_CONF="/etc/ld.so.conf.d/ddcolor-python-nvidia.conf"

source "${CONDA_DIR:-/opt/miniconda}/etc/profile.d/conda.sh"

run_in_env() {
    conda run -p "${ENV_DIR}" "$@"
}

get_cuda_library_dirs() {
    if [[ -d "${NVIDIA_SITE_PACKAGES_DIR}" ]]; then
        find "${NVIDIA_SITE_PACKAGES_DIR}" -mindepth 2 -maxdepth 2 -type d -name lib | sort
    fi
}

get_cuda_library_path() {
    local cuda_library_dirs=()
    local old_ifs

    mapfile -t cuda_library_dirs < <(get_cuda_library_dirs)
    if [[ ${#cuda_library_dirs[@]} -gt 0 ]]; then
        old_ifs="${IFS}"
        IFS=:
        printf '%s' "${cuda_library_dirs[*]}"
        IFS="${old_ifs}"
    fi
}

ensure_nvrtc_compat_links() {
    local nvrtc_dir="${NVIDIA_SITE_PACKAGES_DIR}/cuda_nvrtc/lib"
    local nvrtc_lib
    local nvrtc_builtins_lib

    if [[ ! -d "${nvrtc_dir}" ]]; then
        echo "No CUDA NVRTC library directory found yet at ${nvrtc_dir}."
        return 0
    fi

    if [[ ! -e "${nvrtc_dir}/libnvrtc.so" ]]; then
        nvrtc_lib="$(find "${nvrtc_dir}" -maxdepth 1 -type f -name 'libnvrtc.so.*' | sort -V | tail -n 1)"
        if [[ -n "${nvrtc_lib}" ]]; then
            ln -s "$(basename "${nvrtc_lib}")" "${nvrtc_dir}/libnvrtc.so"
            echo "Created libnvrtc.so compatibility symlink."
        fi
    fi

    if [[ ! -e "${nvrtc_dir}/libnvrtc-builtins.so" ]]; then
        nvrtc_builtins_lib="$(find "${nvrtc_dir}" -maxdepth 1 -type f -name 'libnvrtc-builtins.so.*' | sort -V | tail -n 1)"
        if [[ -n "${nvrtc_builtins_lib}" ]]; then
            ln -s "$(basename "${nvrtc_builtins_lib}")" "${nvrtc_dir}/libnvrtc-builtins.so"
            echo "Created libnvrtc-builtins.so compatibility symlink."
        fi
    fi
}

configure_cuda_library_paths() {
    local cuda_library_dirs=()
    local cuda_library_path

    mapfile -t cuda_library_dirs < <(get_cuda_library_dirs)
    if [[ ${#cuda_library_dirs[@]} -eq 0 ]]; then
        echo "No Python NVIDIA CUDA library directories found yet under ${NVIDIA_SITE_PACKAGES_DIR}."
        return 0
    fi

    cuda_library_path="$(IFS=:; printf '%s' "${cuda_library_dirs[*]}")"

    mkdir -p "${ENV_DIR}/etc/conda/activate.d" "${ENV_DIR}/etc/conda/deactivate.d"
    cat > "${ENV_DIR}/etc/conda/activate.d/ddcolor-cuda-libs.sh" <<EOF
# Generated by .devcontainer/setup-conda-env.sh.
export _DDCOLOR_PREV_LD_LIBRARY_PATH="\${LD_LIBRARY_PATH:-}"
export DDCOLOR_CUDA_LIBRARY_PATH="${cuda_library_path}"
if [[ -n "\${LD_LIBRARY_PATH:-}" ]]; then
    export LD_LIBRARY_PATH="\${DDCOLOR_CUDA_LIBRARY_PATH}:\${LD_LIBRARY_PATH}"
else
    export LD_LIBRARY_PATH="\${DDCOLOR_CUDA_LIBRARY_PATH}"
fi
EOF
    cat > "${ENV_DIR}/etc/conda/deactivate.d/ddcolor-cuda-libs.sh" <<'EOF'
# Generated by .devcontainer/setup-conda-env.sh.
if [[ -n "${_DDCOLOR_PREV_LD_LIBRARY_PATH:-}" ]]; then
    export LD_LIBRARY_PATH="${_DDCOLOR_PREV_LD_LIBRARY_PATH}"
else
    unset LD_LIBRARY_PATH
fi
unset DDCOLOR_CUDA_LIBRARY_PATH
unset _DDCOLOR_PREV_LD_LIBRARY_PATH
EOF

    if command -v sudo >/dev/null 2>&1 && sudo -n true >/dev/null 2>&1; then
        printf '%s\n' "${cuda_library_dirs[@]}" | sudo tee "${CUDA_LD_CONF}" >/dev/null
        sudo ldconfig
        echo "Registered Python NVIDIA CUDA libraries with ldconfig."
    else
        echo "sudo is unavailable; relying on LD_LIBRARY_PATH from conda activation."
    fi
}

install_jupyter_kernel_spec() {
    local cuda_library_path
    local kernel_ld_library_path
    local kernel_json_dirs=(
        "${ENV_DIR}/share/jupyter/kernels/python3"
        "${HOME}/.local/share/jupyter/kernels/ddcolor"
    )
    local kernel_json_dir

    cuda_library_path="$(get_cuda_library_path)"
    kernel_ld_library_path="${cuda_library_path}:${ENV_DIR}/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64"

    for kernel_json_dir in "${kernel_json_dirs[@]}"; do
        mkdir -p "${kernel_json_dir}"
        cat > "${kernel_json_dir}/kernel.json" <<EOF
{
 "argv": [
  "${ENV_DIR}/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "DDColor (Python 3.9, CUDA)",
 "language": "python",
 "env": {
  "LD_LIBRARY_PATH": "${kernel_ld_library_path}"
 },
 "metadata": {
  "debugger": true
 }
}
EOF
    done

    echo "Installed DDColor Jupyter kernelspec with CUDA library paths."
}

validate_onnxruntime_cuda_libraries() {
    local ort_cuda_lib
    local missing_libraries
    local nvrtc_dir="${NVIDIA_SITE_PACKAGES_DIR}/cuda_nvrtc/lib"

    if [[ ! -e "${nvrtc_dir}/libnvrtc.so" ]]; then
        echo "libnvrtc.so compatibility symlink is missing from ${nvrtc_dir}."
        return 1
    fi

    ort_cuda_lib="$(run_in_env python -c '
import pathlib

import onnxruntime as ort

capi_dir = pathlib.Path(ort.__file__).parent / "capi"
for path in capi_dir.glob("libonnxruntime_providers_cuda.so"):
    print(path)
    break
')"

    if [[ -z "${ort_cuda_lib}" ]]; then
        echo "ONNX Runtime CUDA provider library was not found."
        return 1
    fi

    missing_libraries="$(ldd "${ort_cuda_lib}" | awk '/not found/ { print }')"
    if [[ -n "${missing_libraries}" ]]; then
        echo "ONNX Runtime CUDA provider still has unresolved native dependencies:"
        echo "${missing_libraries}"
        return 1
    fi

    echo "ONNX Runtime CUDA provider native dependencies are resolved."
}

# This hash changes when the install commands or dependency files change.
HASH_INPUT_FILE="$(mktemp)"
trap 'rm -f "${HASH_INPUT_FILE}"' EXIT

{
    echo "python=3.9"
    echo "pip"
    echo "conda-channel=conda-forge"
    echo "torch==2.2.0"
    echo "torchvision==0.17.0"
    echo "pytorch-index=https://download.pytorch.org/whl/cu118"
    echo "coloredlogs"
    echo "flatbuffers"
    echo "ipykernel"
    echo "matplotlib"
    echo "numpy"
    echo "onnx==1.16.1"
    echo "packaging"
    echo "protobuf"
    echo "sympy"
    echo "pip-uninstall=onnxruntime"
    echo "onnxruntime-gpu==1.19.2"
    echo "onnxruntime-gpu-index=${ONNXRUNTIME_GPU_INDEX_URL}"
    echo "onnxsim==0.4.36"
    echo "python-nvidia-cuda-libs=ldconfig"
    echo "python-nvidia-cuda-nvrtc=compat-symlinks"
    echo "jupyter-kernelspec=ddcolor-cuda"
    echo "setup.py develop"

    for file in requirements.txt requirements.train.txt setup.py; do
        if [[ -f "${REPO_DIR}/${file}" ]]; then
            sha256sum "${REPO_DIR}/${file}"
        else
            echo "${file} missing"
        fi
    done
} > "${HASH_INPUT_FILE}"

CURRENT_HASH="$(sha256sum "${HASH_INPUT_FILE}" | cut -d ' ' -f 1)"

if [[ -x "${ENV_DIR}/bin/python" && -f "${MARKER_FILE}" && "$(cat "${MARKER_FILE}")" == "${CURRENT_HASH}" ]]; then
    ensure_nvrtc_compat_links
    configure_cuda_library_paths
    install_jupyter_kernel_spec
    validate_onnxruntime_cuda_libraries
    echo "Conda environment '${ENV_NAME}' is already up to date at ${ENV_DIR}."
    exit 0
fi

mkdir -p "${HOME}/.conda/pkgs" "$(dirname "${ENV_DIR}")"

if [[ ! -x "${ENV_DIR}/bin/python" ]]; then
    conda create -y -p "${ENV_DIR}" --override-channels -c conda-forge python=3.9 pip
fi

cd "${REPO_DIR}"

run_in_env python -m pip install --upgrade pip setuptools wheel
run_in_env python -m pip install \
    torch==2.2.0 \
    torchvision==0.17.0 \
    --index-url https://download.pytorch.org/whl/cu118
run_in_env python -m pip install -r requirements.txt
run_in_env python -m pip install \
    coloredlogs \
    flatbuffers \
    ipykernel \
    matplotlib \
    numpy \
    onnx==1.16.1 \
    onnxsim==0.4.36 \
    packaging \
    protobuf \
    sympy
run_in_env python -m pip uninstall -y onnxruntime
run_in_env python -m pip install \
    --index-url "${ONNXRUNTIME_GPU_INDEX_URL}" \
    onnxruntime-gpu==1.19.2
ensure_nvrtc_compat_links
configure_cuda_library_paths
install_jupyter_kernel_spec
validate_onnxruntime_cuda_libraries

if [[ -f requirements.train.txt ]]; then
    run_in_env python -m pip install -r requirements.train.txt
else
    echo "requirements.train.txt not found; skipping separate training requirements."
fi

run_in_env python3 setup.py develop
printf '%s\n' "${CURRENT_HASH}" > "${MARKER_FILE}"
